# Generated by Django 5.2 on 2025-04-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('setbudget', models.IntegerField()),
                ('totalspend', models.IntegerField()),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('balance', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='UserPersonal',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=64)),
                ('balance', models.IntegerField()),
            ],
            options={
                'db_table': 'Personal Users',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tranid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspot.category')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspot.userpersonal')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspot.userpersonal'),
        ),
    ]
